### ISSUE TITLE
pypi workflow should not upload release candidates

### ISSUE THREAD

**Issue by igaw** [linux-nvme/libnvme#429]
The current workflow rule

```yaml
  upload_pypi:
    needs: [build_sdist]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
```

uploads release candidates and marks them as normal release. E.g. v1.1-rc0 was uploaded as v1.1. 

@glimchb
