### ISSUE TITLE
Python upload fails

### ISSUE THREAD

**Issue by igaw** [linux-nvme/libnvme#976]
https://github.com/linux-nvme/libnvme/actions/runs/14068389590/job/39396515053

```
ERROR    InvalidDistribution: Invalid distribution metadata: unrecognized or  malformed field 'description'    
```

It seems that the twine tool chokes on one something.

Some pointers:
- https://packaging.python.org/en/latest/tutorials/packaging-projects/
- https://github.com/pypa/twine/pull/1180/commits/4ae9088614763d40128bd5ef5de9adb87c0a68de

**Comment by igaw** [comment]
@glimchb any idea?

**Comment by glimchb** [comment]
according to similar https://github.com/pypa/twine/issues/1216
this could help:
```
pip install -U packaging
```
before calling `pypa/gh-action-pypi-publish`

**Comment by igaw** [comment]
I've dissabled the action for now as I was too stupid to get it working again.

**Comment by igaw** [comment]
I've tried to use the virtual environment but the action does filter out any special paths. I'm giving up, can't waste more time into this. If someone wants to fix it, please be my guest. Otherwise, PyPi uploads are history.

**Comment by glimchb** [comment]
@igaw let me try and fix it

**Comment by igaw** [comment]
Thanks a lot! I got a bit frustrated with the Github Actions/Workflows. They are great when they work but if not, they are so time consuming to fix. It's difficult to justify the time it takes to get them working...

**Comment by glimchb** [comment]
Agree! Sorry for not jumping on this sooner

**Comment by glimchb** [comment]
@igaw publishing fails on `Error: Trusted publishing exchange failure`
can you fix the trusted publisher in https://test.pypi.org/manage/project/libnvme/settings/publishing/

![Image](https://github.com/user-attachments/assets/f5979f23-f35c-4acb-bb1d-ac5ac95d71e7)

**Comment by igaw** [comment]
Thanks,  the final hurdle was the 'environment'. I alreaddy set it explicitly to 'pypi'. So after adding it, the test upload works again. I've replicated the settings for the release upload. But I don't think I can upload the v1.13 via the action now.

**Comment by glimchb** [comment]
we can add and or statement like this `|| ${{ github.event_name == 'workflow_dispatch' }}` to this line https://github.com/linux-nvme/libnvme/blob/4c189213157c3d95687494b3c2cf013bf12e55f7/.github/workflows/release-python.yml#L63 if you want to...

**Comment by igaw** [comment]
Wouldn't this mean we upload every single merge into master?

What we would be nice is a workflow trigger with an argument, e.g. build a tag with but using the latest workflow version.

**Comment by igaw** [comment]
chatgpt says we would need something like

```yaml
name: Run workflow on a historical tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to check out'
        required: true

jobs:
  run-on-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout specific tag
        run: |
          git fetch --tags
          git checkout ${{ github.event.inputs.tag }}

      - name: Show current commit
        run: git log -1

      - name: Your steps here
        run: |
          echo "Running on tag: ${{ github.event.inputs.tag }}"
          # put your build/test/etc. here
```

From a quick look, it seems to make sense...
